image: ralfjung/opam-ci:latest

iris_atomic-coq8.5.3:
  script:
  # prepare
  - . build/opam-ci.sh 'coq 8.5.3' 'coq-mathcomp-ssreflect 1.6'
  # build
  - 'time make -j8'
  cache:
    key: "coq8.5"
    paths:
    - opamroot/
  only:
  - master
  - ci
